encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random_entry, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms

import random

from django.urls import reverse

from . import util

class searchForm(forms.Form):
    search = forms.CharField(label="Search Encyclopedia")

class newPageForm(forms.Form):
    title = forms.CharField(label="Page Title")
    content = forms.CharField(label="Page Content", widget=forms.Textarea, min_length=1)

class editPageForm(forms.Form):
    content = forms.CharField(label="Page Content", widget=forms.Textarea, min_length=1)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": util.get_entry_html(title),
    })

def search(request):
    if request.method == "POST":
        form = searchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            if util.get_entry(search):
                return render(request, "encyclopedia/entry.html", {
                    "title": search,
                    "content": util.get_entry_html(search),
                })
            else:
                return render(request, "encyclopedia/search.html", {
                    "entries": [entry for entry in util.list_entries() if search.lower() in entry.lower()],
                })
    else:
        return render(request, "encyclopedia/search.html", {
            "entries": util.list_entries(),
        })

def create(request):
    if request.method == "POST":
        form = newPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            try :
                util.save_entry(title, content)
            except FileExistsError:
                return render(request, "encyclopedia/create.html", {
                    "form": form,
                    "error": "Page already exists"
                })
            
            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "content": util.get_entry_html(title),
            })
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form,
                "error": ""
            })
    return render(request, "encyclopedia/create.html", {
        "form": newPageForm(),
        "error": ""
    })

def edit(request, title):
    if request.method == "POST":
        form = editPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            try :
                util.edit_entry(title, content)
            except FileNotFoundError:
                return render(request, "encyclopedia/edit.html", {
                    "form": form,
                    "title": title,
                    "error": "Page not found"
                })
            
            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "content": util.get_entry_html(title),
            })
        else:
            return render(request, "encyclopedia/edit.html", {
                "form": form,
                "title": title,
                "error": ""
            })
    return render(request, "encyclopedia/edit.html", {
        "form": editPageForm(initial={ "content": util.get_entry(title)}),
        "title": title,
        "error": ""
    })
    
def random_entry(request):
    random_title = random.choice(util.list_entries())
        
    return HttpResponseRedirect(f"wiki/{random_title}")

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    {% if error != "" %}
        <p class="form-error">{{ error }}</p>
    {% endif %}

    <form action="{% url 'encyclopedia:create' %}" method="POST" class="d-flex flex-column mw-100">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Publish Page">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit {{ title }}</h1>

    {% if error != "" %}
        <p class="form-error">{{ error }}</p>
    {% endif %}

    <form action="{% url 'encyclopedia:edit' title=title %}" method="POST" class="d-flex flex-column">
        {% csrf_token %}
        <input type="text" value="{{ title }}" disabled>
        {{ form }}
        <input type="submit" value="Publish Changes">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <a href="{% url 'encyclopedia:edit' title=title %}">Edit page</a>
    <div id="content-container">{{ content | safe }}</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row mw-100 m-0">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="search" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">
                        Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9 mw-100 d-flex flex-column">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search</h1>

    {% if entries|length > 0 %}
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}